# Secrets management with environment variables placeholders
openai:
  api_key: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORG}

database:
  url: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}

auth:
  jwt_secret: ${JWT_SECRET_KEY}
  algorithm: HS256